imports:
    - { resource: config_prod.yml }
    - { resource: config_api_doc.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_stage.yml"


monolog:
    handlers:
        main:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            max_files: 10 # Store log for 10 days.
            channels: [!event]
        console:
            type:   console
            channels: [!event, !doctrine]

        # Log all notifications received from queue command.
        queue_command:
            level: info
