nelmio_api_doc:
    name: 'API documentation'
    default_sections_opened: false
    sandbox:
        body_format:
            default_format: json
        authentication:
            delivery: header
            name: Authorization
            type: bearer