<?php

namespace CacheBundle\Repository;

/**
 * UserStoredQueryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserStoredQueryRepository extends \Doctrine\ORM\EntityRepository
{
}
