CREATE DATABASE IF NOT EXISTS socialhose DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS socialhose_test DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
